//! Active-context projection and authoritative pointer annotations.

use std::collections::BTreeSet;
use std::fmt;

use agent_runtime_core::content::{ContentPart, Message};
use agent_runtime_core::ids::ToolCallId;
use agent_runtime_registry::{Fingerprint, FingerprintHasher, RegistryRevision};
use serde::{Deserialize, Serialize};

use crate::classification::LcmClassification;
use crate::entry::LcmEntry;
use crate::ids::{LcmNodeId, LcmRange, LcmRevision, LcmSequence, LcmTimelineId};
use crate::node::{LcmNode, LcmNodeKind};
use crate::planning::source_fingerprint_entries;
use crate::store::LcmError;
use crate::summarize::SummaryProvenance;

/// Validated pointer metadata generated by the runtime, never accepted from
/// summary model text.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LcmPointerAnnotation {
    /// Timeline identity bound by the host.
    pub timeline_id: LcmTimelineId,
    /// Node identity to expand through an authorized store view.
    pub node_id: LcmNodeId,
    /// Exact source range covered by the node.
    pub range: LcmRange,
    /// DAG revision at which the node was committed.
    pub revision: LcmRevision,
    /// Exact source fingerprint.
    pub source_fingerprint: Fingerprint,
}

impl LcmPointerAnnotation {
    /// Creates an annotation from validated node metadata.
    pub fn from_node(node: &LcmNode) -> Self {
        Self {
            timeline_id: node.timeline_id.clone(),
            node_id: node.id.clone(),
            range: node.range,
            revision: node.revision,
            source_fingerprint: node.source_fingerprint.clone(),
        }
    }

    /// Stable provider-visible annotation text. It is a lookup key, not an
    /// authority grant.
    pub fn render(&self) -> String {
        format!(
            "[lcm node={} timeline={} range={}-{} revision={} source={}]",
            self.node_id,
            self.timeline_id,
            self.range.start,
            self.range.end,
            self.revision,
            self.source_fingerprint
        )
    }
}

/// A projected context body. Hosts map candidates to their own versioned
/// context fragments and let the authoritative planner budget them.
#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub enum LcmCandidateContent {
    /// Committed summary body plus the runtime-generated pointer.
    Summary {
        /// Summary text from the authorized committed node.
        text: String,
        /// Authoritative pointer metadata.
        pointer: LcmPointerAnnotation,
    },
    /// Immutable canonical message.
    Message(Message),
}

impl fmt::Debug for LcmCandidateContent {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Summary { text: _, pointer } => formatter
                .debug_struct("LcmCandidateContent::Summary")
                .field("text", &"[redacted]")
                .field("pointer", pointer)
                .finish(),
            Self::Message(message) => formatter
                .debug_struct("LcmCandidateContent::Message")
                .field("role", &message.role)
                .field("part_count", &message.content.len())
                .field("body", &"[redacted]")
                .finish(),
        }
    }
}

/// One versioned candidate returned to the host context planner.
#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub struct LcmContextCandidate {
    /// Stable candidate identity (`node:<id>` or `entry:<id>`).
    pub id: String,
    /// Exact source sequence range represented by this candidate.
    pub range: LcmRange,
    /// Candidate content; LCM does not serialize it into a provider request.
    pub content: LcmCandidateContent,
    /// Content/body revision.
    pub revision: RegistryRevision,
    /// Joined source classification.
    pub classification: LcmClassification,
    /// Tool-call/result identities owned or answered by this candidate.
    pub pairings: BTreeSet<ToolCallId>,
}

impl fmt::Debug for LcmContextCandidate {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LcmContextCandidate")
            .field("id", &Fingerprint::of(self.id.as_bytes()))
            .field("range", &self.range)
            .field("content", &self.content)
            .field("revision", &self.revision)
            .field("classification", &self.classification)
            .field("pairing_count", &self.pairings.len())
            .finish()
    }
}

impl LcmContextCandidate {
    /// Whether this candidate represents a summary node.
    pub fn is_summary(&self) -> bool {
        matches!(self.content, LcmCandidateContent::Summary { .. })
    }

    /// Returns summary text, if this candidate is a summary. Raw messages
    /// remain structured so hosts can map them to canonical fragments.
    pub fn summary_text(&self) -> Option<&str> {
        match &self.content {
            LcmCandidateContent::Summary { text, .. } => Some(text),
            LcmCandidateContent::Message(_) => None,
        }
    }
}

/// Either a committed active node or an uncovered raw entry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum ProjectionItem {
    /// Active summary node and authoritative pointer.
    Node {
        /// Node metadata/body.
        node: LcmNode,
        /// Generated pointer annotation.
        pointer: LcmPointerAnnotation,
    },
    /// Uncovered immutable raw entry.
    Entry(LcmEntry),
}

/// Deterministic active projection for one DAG revision.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ActiveProjection {
    /// Logical timeline.
    pub timeline_id: LcmTimelineId,
    /// Revision used to derive this projection.
    pub revision: LcmRevision,
    /// Canonical active items.
    pub items: Vec<ProjectionItem>,
    /// Versioned candidates for the host planner.
    pub candidates: Vec<LcmContextCandidate>,
    /// Last represented source sequence, if any.
    pub frontier: Option<LcmSequence>,
    /// Fingerprint of projection identities/revisions, never bodies.
    pub fingerprint: Fingerprint,
}

/// Projects active nodes followed by every uncovered raw entry in canonical
/// source order. Raw entries covered by a node are not duplicated.
pub fn project_active_context(
    timeline_id: &LcmTimelineId,
    revision: LcmRevision,
    active_nodes: &[LcmNode],
    raw_entries: &[LcmEntry],
) -> Result<ActiveProjection, LcmError> {
    project_active_context_with_suffix(timeline_id, revision, active_nodes, raw_entries, None)
}

/// Variant allowing a host to retain only a recent raw suffix after the active
/// frontier. `None` retains all uncovered raw entries.
pub fn project_active_context_with_suffix(
    timeline_id: &LcmTimelineId,
    revision: LcmRevision,
    active_nodes: &[LcmNode],
    raw_entries: &[LcmEntry],
    recent_raw_start: Option<LcmSequence>,
) -> Result<ActiveProjection, LcmError> {
    let mut nodes = active_nodes.to_vec();
    nodes.sort_by_key(|node| (node.range.start, node.range.end, node.id.clone()));
    let mut entries = raw_entries.to_vec();
    entries.sort_by_key(|entry| (entry.sequence, entry.id.clone()));
    validate_projection_inputs(timeline_id, &nodes, &entries)?;
    if let Some(start) = recent_raw_start {
        let expected_start = nodes
            .last()
            .and_then(|node| node.range.end.next())
            .unwrap_or(LcmSequence::new(0));
        if start > expected_start {
            return Err(LcmError::Invalid {
                reason: "raw suffix starts after an uncovered frontier gap".into(),
            });
        }
        for entry in entries.iter().filter(|entry| entry.sequence < start) {
            if !nodes.iter().any(|node| node.range.contains(entry.sequence)) {
                return Err(LcmError::Invalid {
                    reason: "raw suffix would omit an uncovered timeline entry".into(),
                });
            }
        }
    }

    let mut items = Vec::new();
    let mut entry_index = 0_usize;
    for node in &nodes {
        while entry_index < entries.len() && entries[entry_index].sequence < node.range.start {
            if recent_raw_start.is_none_or(|start| entries[entry_index].sequence >= start) {
                items.push(ProjectionItem::Entry(entries[entry_index].clone()));
            }
            entry_index += 1;
        }
        let pointer = LcmPointerAnnotation::from_node(node);
        items.push(ProjectionItem::Node {
            node: node.clone(),
            pointer,
        });
        while entry_index < entries.len() && node.range.contains(entries[entry_index].sequence) {
            entry_index += 1;
        }
    }
    while entry_index < entries.len() {
        if recent_raw_start.is_none_or(|start| entries[entry_index].sequence >= start) {
            items.push(ProjectionItem::Entry(entries[entry_index].clone()));
        }
        entry_index += 1;
    }

    let candidates = items.iter().map(candidate_from_item).collect::<Vec<_>>();
    let frontier = items.iter().map(item_end).max();
    let fingerprint = projection_fingerprint(timeline_id, revision, &items);
    Ok(ActiveProjection {
        timeline_id: timeline_id.clone(),
        revision,
        items,
        candidates,
        frontier,
        fingerprint,
    })
}

fn validate_projection_inputs(
    timeline_id: &LcmTimelineId,
    nodes: &[LcmNode],
    entries: &[LcmEntry],
) -> Result<(), LcmError> {
    for node in nodes {
        if node.timeline_id != *timeline_id || !node.is_active() {
            return Err(LcmError::CrossTimeline);
        }
        node.validate()
            .map_err(|reason| LcmError::Invalid { reason })?;
    }
    for entry in entries {
        if entry.timeline_id != *timeline_id {
            return Err(LcmError::CrossTimeline);
        }
        entry
            .validate()
            .map_err(|reason| LcmError::Invalid { reason })?;
    }
    for pair in nodes.windows(2) {
        if pair[0].range.overlaps(pair[1].range) {
            return Err(LcmError::RangeOverlap);
        }
        if !pair[0].range.is_adjacent_to(pair[1].range) {
            return Err(LcmError::Invalid {
                reason: "active nodes must form one canonical prefix".into(),
            });
        }
    }
    for pair in entries.windows(2) {
        let Some(expected) = pair[0].sequence.next() else {
            return Err(LcmError::Invalid {
                reason: "raw sequence space is exhausted".into(),
            });
        };
        if pair[1].sequence != expected {
            return Err(LcmError::Invalid {
                reason: "raw entries must be contiguous and ordered".into(),
            });
        }
    }
    for node in nodes {
        if node.kind != LcmNodeKind::Leaf {
            continue;
        }
        let covered = entries
            .iter()
            .filter(|entry| node.range.contains(entry.sequence))
            .collect::<Vec<_>>();
        if covered.is_empty() {
            continue;
        }
        if covered.len() as u64 != node.range.len() {
            return Err(LcmError::Invalid {
                reason: "raw entries only partially describe a covered leaf".into(),
            });
        }
        let expected_ids = node.entry_ids().cloned().collect::<Vec<_>>();
        let actual_ids = covered
            .iter()
            .map(|entry| entry.id.clone())
            .collect::<Vec<_>>();
        if expected_ids != actual_ids
            || source_fingerprint_entries(&covered.into_iter().cloned().collect::<Vec<_>>())
                != node.source_fingerprint
        {
            return Err(LcmError::Invalid {
                reason: "raw entries disagree with the covered leaf provenance".into(),
            });
        }
    }
    if let Some(first_node) = nodes.first() {
        if first_node.range.start != LcmSequence::new(0) {
            return Err(LcmError::Invalid {
                reason: "active nodes must begin at the timeline frontier".into(),
            });
        }
        if entries
            .iter()
            .any(|entry| entry.sequence < first_node.range.start)
        {
            return Err(LcmError::Invalid {
                reason: "raw entries cannot precede the active prefix".into(),
            });
        }
        if let Some(frontier) = nodes.last().and_then(|node| node.range.end.next()) {
            if let Some(first_uncovered) = entries
                .iter()
                .find(|entry| entry.sequence > nodes.last().expect("first implies last").range.end)
            {
                if first_uncovered.sequence != frontier {
                    return Err(LcmError::Invalid {
                        reason: "raw suffix has a frontier gap".into(),
                    });
                }
            }
        }
    } else if entries
        .first()
        .is_some_and(|entry| entry.sequence != LcmSequence::new(0))
    {
        return Err(LcmError::Invalid {
            reason: "raw-only projection must begin at the timeline frontier".into(),
        });
    }
    Ok(())
}

fn candidate_from_item(item: &ProjectionItem) -> LcmContextCandidate {
    match item {
        ProjectionItem::Node { node, pointer } => LcmContextCandidate {
            id: format!("node:{}", node.id),
            range: node.range,
            content: LcmCandidateContent::Summary {
                text: node.summary.clone(),
                pointer: pointer.clone(),
            },
            revision: node.summary_revision.clone(),
            classification: node.classification.clone(),
            pairings: BTreeSet::new(),
        },
        ProjectionItem::Entry(entry) => LcmContextCandidate {
            id: format!("entry:{}", entry.id),
            range: LcmRange::single(entry.sequence),
            content: LcmCandidateContent::Message(entry.content.clone()),
            revision: RegistryRevision::from_content(entry.content_fingerprint.as_str()),
            classification: entry.source.classification.clone(),
            pairings: entry_pairings(entry),
        },
    }
}

fn entry_pairings(entry: &LcmEntry) -> BTreeSet<ToolCallId> {
    entry
        .content
        .content
        .iter()
        .filter_map(|part| match part {
            ContentPart::ToolCall(call) => Some(call.id.clone()),
            ContentPart::ToolResult(result) => Some(result.call_id.clone()),
            _ => None,
        })
        .collect()
}

fn item_end(item: &ProjectionItem) -> LcmSequence {
    match item {
        ProjectionItem::Node { node, .. } => node.range.end,
        ProjectionItem::Entry(entry) => entry.sequence,
    }
}

fn projection_fingerprint(
    timeline_id: &LcmTimelineId,
    revision: LcmRevision,
    items: &[ProjectionItem],
) -> Fingerprint {
    let mut hasher = FingerprintHasher::new();
    hasher.field("projection");
    hasher.field(timeline_id.as_str());
    hasher.field(revision.get().to_string());
    for item in items {
        match item {
            ProjectionItem::Node { node, pointer } => {
                hasher.field("node");
                hasher.field(node.id.as_str());
                hasher.field(node.source_fingerprint.as_str());
                hasher.field(pointer.revision.get().to_string());
                hasher.field(node.summary_revision.as_str());
                hasher.field(node.policy_revision.as_str());
                hasher.field(node.algorithm_revision.as_str());
                hasher.field(node.sizer_revision.as_str());
                hasher.field(node.classification.sensitivity.as_str());
                hasher.field(node.classification.trust.as_str());
                if let Some(revision) = &node.classification.guard_revision {
                    hasher.field("guard_revision");
                    hasher.field(revision.as_str());
                }
                for revision in &node.classification.guard_revisions {
                    hasher.field("guard_revision_set");
                    hasher.field(revision);
                }
                if let Some(revision) = &node.classification.transformation_revision {
                    hasher.field("transformation_revision");
                    hasher.field(revision.as_str());
                }
                for revision in &node.classification.transformation_revisions {
                    hasher.field("transformation_revision_set");
                    hasher.field(revision);
                }
                hasher.field(node.token_count.to_string());
                hasher.field(node.source_token_count.to_string());
                hasher.field(node.operation_fingerprint.as_str());
                match &node.provenance {
                    SummaryProvenance::Model {
                        id,
                        revision,
                        purpose,
                        level,
                    } => {
                        hasher.field("model_provenance");
                        hasher.field(id);
                        hasher.field(revision.as_str());
                        hasher.field(purpose);
                        hasher.field(level.number().to_string());
                    }
                    SummaryProvenance::Deterministic { revision } => {
                        hasher.field("deterministic_provenance");
                        hasher.field(revision.as_str());
                    }
                }
            }
            ProjectionItem::Entry(entry) => {
                hasher.field("entry");
                hasher.field(entry.id.as_str());
                hasher.field(entry.content_fingerprint.as_str());
                hasher.field(source_fingerprint_entries(std::slice::from_ref(entry)).as_str());
            }
        }
    }
    hasher.finish()
}

#[cfg(test)]
mod tests {
    use agent_runtime_context::Sensitivity;
    use agent_runtime_registry::TrustClass;

    use super::*;
    use crate::classification::{LcmClassification, LcmSourceMetadata};
    use crate::entry::LcmEntry;
    use crate::ids::{LcmEntryId, LcmNodeId, LcmOperationFingerprint, LcmOperationId};
    use crate::node::{LcmEdge, LcmNodeKind};
    use crate::summarize::SummaryProvenance;

    fn source() -> LcmSourceMetadata {
        LcmSourceMetadata::new(LcmClassification::new(
            Sensitivity::Internal,
            TrustClass::UserContent,
        ))
    }

    fn raw(sequence: u64) -> LcmEntry {
        LcmEntry::new(
            LcmTimelineId::new("timeline"),
            LcmEntryId::new(format!("e{sequence}")),
            LcmSequence::new(sequence),
            Message::user(format!("raw-{sequence}")),
            source(),
        )
    }

    fn node() -> LcmNode {
        LcmNode {
            timeline_id: LcmTimelineId::new("timeline"),
            id: LcmNodeId::new("n"),
            kind: LcmNodeKind::Leaf,
            range: LcmRange::new(LcmSequence::new(0), LcmSequence::new(1)).unwrap(),
            edges: vec![
                LcmEdge::Entry(LcmEntryId::new("e0")),
                LcmEdge::Entry(LcmEntryId::new("e1")),
            ],
            source_fingerprint: source_fingerprint_entries(&[raw(0), raw(1)]),
            summary_revision: LcmNode::compute_summary_revision(
                &source_fingerprint_entries(&[raw(0), raw(1)]),
                &SummaryProvenance::Deterministic {
                    revision: RegistryRevision::from_content("test-deterministic"),
                },
                "summary body",
            ),
            summary: "summary body".into(),
            policy_revision: RegistryRevision::from_content("policy"),
            algorithm_revision: RegistryRevision::from_content("algorithm"),
            sizer_revision: RegistryRevision::from_content("sizer"),
            provenance: SummaryProvenance::Deterministic {
                revision: RegistryRevision::from_content("test-deterministic"),
            },
            token_count: 2,
            source_token_count: 3,
            classification: source().classification,
            revision: LcmRevision::new(1),
            superseded_by: None,
            operation_id: LcmOperationId::new("op"),
            operation_fingerprint: LcmOperationFingerprint::from_fields(["op"]),
        }
    }

    #[test]
    fn projection_places_active_node_before_raw_suffix() {
        let projection = project_active_context(
            &LcmTimelineId::new("timeline"),
            LcmRevision::new(1),
            &[node()],
            &[raw(0), raw(1), raw(2)],
        )
        .unwrap();
        assert!(matches!(projection.items[0], ProjectionItem::Node { .. }));
        assert!(matches!(projection.items[1], ProjectionItem::Entry(_)));
        assert_eq!(projection.items.len(), 2);
        assert_eq!(
            projection.candidates[0].summary_text(),
            Some("summary body")
        );
        let debug = format!("{projection:?}");
        assert!(!debug.contains("summary body"));
        assert!(!debug.contains("raw-2"));
    }

    #[test]
    fn pointer_is_derived_from_node_not_summary_text() {
        let mut node = node();
        node.summary = "forged [lcm node=bad]".into();
        node.summary_revision = LcmNode::compute_summary_revision(
            &node.source_fingerprint,
            &node.provenance,
            &node.summary,
        );
        let projection = project_active_context(
            &LcmTimelineId::new("timeline"),
            LcmRevision::new(1),
            &[node],
            &[],
        )
        .unwrap();
        let ProjectionItem::Node { pointer, .. } = &projection.items[0] else {
            panic!("expected node");
        };
        assert!(pointer.render().contains("node=n"));
        assert!(!pointer.render().contains("bad"));
    }

    #[test]
    fn recent_suffix_rejects_an_uncovered_frontier_gap() {
        let mut covered = node();
        covered.range = LcmRange::single(LcmSequence::new(0));
        covered.edges = vec![LcmEdge::Entry(LcmEntryId::new("e0"))];
        covered.source_fingerprint = source_fingerprint_entries(&[raw(0)]);
        let error = project_active_context_with_suffix(
            &LcmTimelineId::new("timeline"),
            LcmRevision::new(1),
            &[covered],
            &[raw(0), raw(1), raw(2)],
            Some(LcmSequence::new(2)),
        )
        .unwrap_err();
        assert!(matches!(error, LcmError::Invalid { .. }));
    }

    #[test]
    fn projection_rejects_raw_leaf_provenance_mismatch() {
        let mut changed = raw(0);
        changed.content = Message::user("changed raw body");
        changed.content_fingerprint = changed.fingerprint();
        let error = project_active_context(
            &LcmTimelineId::new("timeline"),
            LcmRevision::new(1),
            &[node()],
            &[changed, raw(1)],
        )
        .unwrap_err();
        assert!(matches!(error, LcmError::Invalid { .. }));
    }

    #[test]
    fn projection_rejects_interleaved_active_nodes_and_raw_gap() {
        let first = node();
        let mut second = node();
        second.id = LcmNodeId::new("n2");
        second.range = LcmRange::single(LcmSequence::new(3));
        second.edges = vec![LcmEdge::Entry(LcmEntryId::new("e3"))];
        let error = project_active_context(
            &LcmTimelineId::new("timeline"),
            LcmRevision::new(1),
            &[first, second],
            &[raw(0), raw(1), raw(2), raw(3)],
        )
        .unwrap_err();
        assert!(matches!(error, LcmError::Invalid { .. }));
    }
}
