/// Describes how a provider kind authenticates.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderAuthMethod {
    /// Standard API key (env var or config).
    ApiKey,
    /// OpenAI-style OAuth flow.
    OAuth,
    /// Claude setup-token (`sk-ant-oat01-…`).
    SetupToken,
    /// No authentication required (local providers).
    None,
}

/// OAuth flow configuration for providers that use OAuth.
#[derive(Debug, Clone)]
pub struct OAuthConfig {
    pub client_id: &'static str,
    pub authorize_url: &'static str,
    pub token_url: &'static str,
    pub device_url: &'static str,
    pub redirect_uri: &'static str,
    pub scopes: &'static [&'static str],
    /// Extra query params to append to the authorize URL.
    pub extra_params: &'static [(&'static str, &'static str)],
}

/// Setup-token configuration for providers that use setup-tokens.
#[derive(Debug, Clone)]
pub struct SetupTokenConfig {
    pub prefix: &'static str,
    pub min_length: usize,
}

/// Static metadata for a supported provider kind.
#[derive(Debug, Clone)]
pub struct ProviderCatalogEntry {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub auth_method: ProviderAuthMethod,
    pub default_env_var: Option<&'static str>,
    pub default_base_url: Option<&'static str>,
    pub default_model: Option<&'static str>,
    pub requires_base_url: bool,
    pub feature_gate: Option<&'static str>,
    pub description: &'static str,
    /// Identifier used for token/profile storage (e.g. "anthropic", "openai-codex").
    pub provider_id: &'static str,
    /// OAuth configuration (only for `ProviderAuthMethod::OAuth`).
    pub oauth: Option<&'static OAuthConfig>,
    /// Setup-token configuration (only for `ProviderAuthMethod::SetupToken`).
    pub setup_token: Option<&'static SetupTokenConfig>,
}

impl ProviderCatalogEntry {
    /// Returns true if `input` matches the canonical name or any alias.
    pub fn matches(&self, input: &str) -> bool {
        self.name == input || self.aliases.contains(&input)
    }
}

/// Look up a catalog entry by name or alias.
pub fn lookup(name: &str) -> Option<&'static ProviderCatalogEntry> {
    PROVIDER_CATALOG.iter().find(|e| e.matches(name))
}

// ---------------------------------------------------------------------------
// Auth configs (provider-specific knowledge lives here, not in the binary)
// ---------------------------------------------------------------------------

static OPENAI_CODEX_OAUTH: OAuthConfig = OAuthConfig {
    client_id: "app_EMoamEEZ73f0CkXaXp7hrann",
    authorize_url: "https://auth.openai.com/oauth/authorize",
    token_url: "https://auth.openai.com/oauth/token",
    device_url: "https://auth.openai.com/oauth/device/code",
    redirect_uri: "http://localhost:1455/auth/callback",
    scopes: &["openid", "profile", "email", "offline_access"],
    extra_params: &[
        ("id_token_add_organizations", "true"),
        ("codex_cli_simplified_flow", "true"),
        ("originator", "nyx"),
    ],
};

static ANTHROPIC_OAUTH: OAuthConfig = OAuthConfig {
    client_id: "9d1c250a-e61b-44e4-8ec0-c3e28a674613",
    authorize_url: "https://auth.anthropic.com/oauth/authorize",
    token_url: "https://auth.anthropic.com/oauth/token",
    device_url: "https://auth.anthropic.com/oauth/device/code",
    redirect_uri: "http://localhost:1455/auth/callback",
    scopes: &["openid", "profile", "email", "offline_access"],
    extra_params: &[],
};

static CLAUDE_SETUP_TOKEN: SetupTokenConfig = SetupTokenConfig {
    prefix: "sk-ant-oat01-",
    min_length: 80,
};

// ---------------------------------------------------------------------------
// Catalog
// ---------------------------------------------------------------------------

/// The full catalog of supported provider kinds.
pub static PROVIDER_CATALOG: &[ProviderCatalogEntry] = &[
    ProviderCatalogEntry {
        name: "openai",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("OPENAI_API_KEY"),
        default_base_url: None,
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("openai"),
        description: "OpenAI (GPT-4o, o3, etc.)",
        provider_id: "openai",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "claude",
        aliases: &["anthropic"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("ANTHROPIC_API_KEY"),
        default_base_url: None,
        default_model: Some("claude-sonnet-4-20250514"),
        requires_base_url: false,
        feature_gate: Some("claude"),
        description: "Anthropic Claude (API key)",
        provider_id: "anthropic",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "claude-code",
        aliases: &["claude_code"],
        auth_method: ProviderAuthMethod::SetupToken,
        default_env_var: None,
        default_base_url: None,
        default_model: Some("claude-sonnet-4-20250514"),
        requires_base_url: false,
        feature_gate: Some("claude"),
        description: "Claude Code (setup-token from `claude setup-token`)",
        provider_id: "anthropic",
        oauth: Some(&ANTHROPIC_OAUTH),
        setup_token: Some(&CLAUDE_SETUP_TOKEN),
    },
    ProviderCatalogEntry {
        name: "openai-codex",
        aliases: &["openai_codex", "codex"],
        auth_method: ProviderAuthMethod::OAuth,
        default_env_var: None,
        default_base_url: Some("https://chatgpt.com/backend-api"),
        default_model: Some("gpt-5.4"),
        requires_base_url: false,
        feature_gate: Some("codex"),
        description: "OpenAI Codex (OAuth)",
        provider_id: "openai-codex",
        oauth: Some(&OPENAI_CODEX_OAUTH),
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "compat",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("OPENAI_API_KEY"),
        default_base_url: None,
        default_model: None,
        requires_base_url: true,
        feature_gate: Some("compat"),
        description: "OpenAI-compatible endpoint (custom base_url)",
        provider_id: "compat",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "ollama",
        aliases: &[],
        auth_method: ProviderAuthMethod::None,
        default_env_var: None,
        default_base_url: Some("http://localhost:11434/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Ollama (local)",
        provider_id: "ollama",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "lmstudio",
        aliases: &["lm-studio"],
        auth_method: ProviderAuthMethod::None,
        default_env_var: None,
        default_base_url: Some("http://localhost:1234/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "LM Studio (local)",
        provider_id: "lmstudio",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "openrouter",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("OPENROUTER_API_KEY"),
        default_base_url: Some("https://openrouter.ai/api/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "OpenRouter",
        provider_id: "openrouter",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "groq",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("GROQ_API_KEY"),
        default_base_url: Some("https://api.groq.com/openai/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Groq",
        provider_id: "groq",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "mistral",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("MISTRAL_API_KEY"),
        default_base_url: Some("https://api.mistral.ai/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Mistral AI",
        provider_id: "mistral",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "xai",
        aliases: &["grok"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("XAI_API_KEY"),
        default_base_url: Some("https://api.x.ai/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "xAI (Grok)",
        provider_id: "xai",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "deepseek",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("DEEPSEEK_API_KEY"),
        default_base_url: Some("https://api.deepseek.com"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "DeepSeek",
        provider_id: "deepseek",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "together",
        aliases: &["together-ai"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("TOGETHER_API_KEY"),
        default_base_url: Some("https://api.together.xyz/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Together AI",
        provider_id: "together",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "fireworks",
        aliases: &["fireworks-ai"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("FIREWORKS_API_KEY"),
        default_base_url: Some("https://api.fireworks.ai/inference/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Fireworks AI",
        provider_id: "fireworks",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "perplexity",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("PERPLEXITY_API_KEY"),
        default_base_url: Some("https://api.perplexity.ai"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Perplexity",
        provider_id: "perplexity",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "cohere",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("COHERE_API_KEY"),
        default_base_url: Some("https://api.cohere.com/compatibility/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Cohere",
        provider_id: "cohere",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "nvidia",
        aliases: &["nvidia-nim"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("NVIDIA_API_KEY"),
        default_base_url: Some("https://integrate.api.nvidia.com/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "NVIDIA NIM",
        provider_id: "nvidia",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "venice",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("VENICE_API_KEY"),
        default_base_url: Some("https://api.venice.ai/api/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Venice AI",
        provider_id: "venice",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "moonshot",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("MOONSHOT_API_KEY"),
        default_base_url: Some("https://api.moonshot.cn/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Moonshot AI",
        provider_id: "moonshot",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "glm",
        aliases: &["chatglm", "zhipu"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("GLM_API_KEY"),
        default_base_url: Some("https://open.bigmodel.cn/api/paas/v4"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "ChatGLM / Zhipu AI",
        provider_id: "glm",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "minimax",
        aliases: &[],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("MINIMAX_API_KEY"),
        default_base_url: Some("https://api.minimax.chat/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "MiniMax",
        provider_id: "minimax",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "qwen",
        aliases: &["dashscope", "aliyun"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("DASHSCOPE_API_KEY"),
        default_base_url: Some("https://dashscope.aliyuncs.com/compatible-mode/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Qwen / DashScope (Alibaba)",
        provider_id: "qwen",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "qianfan",
        aliases: &["baidu"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("QIANFAN_API_KEY"),
        default_base_url: Some("https://aip.baidubce.com"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Qianfan (Baidu)",
        provider_id: "qianfan",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "bedrock",
        aliases: &["aws-bedrock"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("AWS_BEARER_TOKEN_BEDROCK"),
        default_base_url: Some("https://bedrock-runtime.us-east-1.amazonaws.com"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "AWS Bedrock",
        provider_id: "bedrock",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "vercel",
        aliases: &["vercel-ai"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("VERCEL_API_KEY"),
        default_base_url: Some("https://api.vercel.ai/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Vercel AI",
        provider_id: "vercel",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "cloudflare",
        aliases: &["cloudflare-ai"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("CLOUDFLARE_API_KEY"),
        default_base_url: Some("https://gateway.ai.cloudflare.com/v1"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Cloudflare AI",
        provider_id: "cloudflare",
        oauth: None,
        setup_token: None,
    },
    ProviderCatalogEntry {
        name: "zai",
        aliases: &["z.ai"],
        auth_method: ProviderAuthMethod::ApiKey,
        default_env_var: Some("ZAI_API_KEY"),
        default_base_url: Some("https://api.z.ai/api/coding/paas/v4"),
        default_model: None,
        requires_base_url: false,
        feature_gate: Some("compat"),
        description: "Z.AI",
        provider_id: "zai",
        oauth: None,
        setup_token: None,
    },
];
